### PR TITLE
support both pyside and pyqt

### PR DESCRIPTION
**Pull request by mvgorcum**
This is basically a copy of what pyqtgraph does to support both pyside and pyqt.
Let me know if this is acceptable to you.

Ps. Hoi Dennis! Leuke library.

### CODE REVIEW

**Comment by Dennis-van-Gils** [comment]
Thanks Mathijs. I'll have a closer look in the coming month. I need to be sure nothing breaks in the other projects that rely on this library. It is used, among other things, for a practicum at the UT where I locked the python version to 3.8. But adding support for PySide sounds like a good plan.

**Comment by mvgorcum** [comment]
Hi Dennis,

Any update on this? I'm considering using this in production so if it doesn't fit with your project I'll probably maintain a fork and upload that to pypi, but I'd of course be happier to just upstream these small changes.

**Comment by Dennis-van-Gils** [comment]
Hi Mathijs,
I'll go into it after my holidays that start soon.

**Comment by Dennis-van-Gils** [comment]
One thing puzzles me. Why do you assign the variables `QtCore`, `QtGui` and `QtWid` to themselves again?

**Comment by Dennis-van-Gils** [comment]
Hi Mathijs. I have finished adding support for PyQt5, PyQt6, PySide2 and PySide6. Your pull request was a very handy basis, but a few more changes had to be made in other parts of the code as well. They involve the use of Qt enumerations and `app.exec()`, see https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/. All Qt libraries are tested in Python 3.9 and work fine. I'm closing the pull without merging. Thanks again.

**Comment by mvgorcum** [comment]
Thanks for taking the time to go through it!

**Pull request closed without merging**
